[CI] Add a manually triggered release workflow (#156)
* Add a manually triggered release workflow

* Restructure workflow

* Run build-jar and build-wheel in parallel

* Don't need JDK when running the release job

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,9 +22,174 @@ on:
         type: boolean
         default: true
 
+env:
+  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
+
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
     steps:
-      - name: Placeholder
-        run: echo "placeholder"
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          java-version: '8'
+          distribution: 'zulu'
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+      - name: Resolve version number
+        id: resolve-version
+        run: |
+          export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "Project version number: $VERSION"
+          if [ -z "$VERSION" ]; then
+            echo "::error title=Resolve version number failed::Failed to obtain version number of this maven project"
+          fi
+          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
+            echo "::error title=SNAPSHOT version detected::The version $VERSION is a snapshot version and should not be released"
+            exit 1
+          fi
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+          echo "tag=v${VERSION}" >> "$GITHUB_OUTPUT"
+    outputs:
+      version: ${{ steps.resolve-version.outputs.version }}
+      tag: ${{ steps.resolve-version.outputs.tag }}
+
+  build-wheel:
+    needs:
+      - prepare
+    uses: wherobots/wherobots-compute/.github/workflows/python-wheel.yml@master
+
+  build-jars:
+    runs-on: ubuntu-latest
+    needs:
+      - prepare
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          java-version: '8'
+          distribution: 'zulu'
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+      - name: Delete existing maven package
+        if: ${{ github.event.inputs.overwrite != 'false' }}
+        env:
+          VERSION: ${{ needs.prepare.outputs.version }}
+          TAG: ${{ needs.prepare.outputs.tag }}
+          GITHUB_TOKEN: ${{ secrets.GH_PKG_GITHUB_TOKEN }}
+        run: |
+          export GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
+          echo "Finding all artifact IDs"
+          find . -name pom.xml -execdir sh -c 'echo "$(mvn help:evaluate -Dexpression=project.artifactId -Dscala=2.12 -Dspark=3.0 -q -DforceStdout)"' \; > artifact-list.txt
+          find . -name pom.xml -execdir sh -c 'echo "$(mvn help:evaluate -Dexpression=project.artifactId -Dscala=2.12 -Dspark=3.4 -q -DforceStdout)"' \; >> artifact-list.txt
+          find . -name pom.xml -execdir sh -c 'echo "$(mvn help:evaluate -Dexpression=project.artifactId -Dscala=2.12 -Dspark=3.5 -q -DforceStdout)"' \; >> artifact-list.txt
+          sort artifact-list.txt | uniq | sed "s/^/${GROUP_ID}./" > package-list.txt
+          echo "Packages to be deleted:"
+          cat package-list.txt
+          echo "Deleting package version $VERSION"
+          python3 .github/workflows/scripts/delete_gh_packages.py --owner wherobots --repo packages --package-type maven --package-list package-list.txt --version $VERSION
+      - name: Build and publish to Maven repository
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PKG_GITHUB_TOKEN }}
+        run: |
+          mkdir -p artifacts/jars
+          mvn --batch-mode clean deploy -DskipTests -Dscala=2.12 -Dspark=3.0
+          cp spark-shaded/target/sedona-*.jar artifacts/jars
+          cp flink-shaded/target/sedona-*.jar artifacts/jars
+          cp snowflake/target/sedona-*.jar artifacts/jars
+          mvn --batch-mode clean deploy -DskipTests -Dscala=2.12 -Dspark=3.4
+          cp spark-shaded/target/sedona-*.jar artifacts/jars
+          cp flink-shaded/target/sedona-*.jar artifacts/jars
+          cp snowflake/target/sedona-*.jar artifacts/jars
+          mvn --batch-mode clean deploy -DskipTests -Dscala=2.12 -Dspark=3.5
+          cp spark-shaded/target/sedona-*.jar artifacts/jars
+          cp flink-shaded/target/sedona-*.jar artifacts/jars
+          cp snowflake/target/sedona-*.jar artifacts/jars
+      - uses: actions/upload-artifact@v3
+        with:
+          name: jars
+          path: ./artifacts/jars/*
+
+  release:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      packages: write
+    needs:
+      - prepare
+      - build-jars
+      - build-wheel
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+      - name: Install python dependencies
+        run: python3 -m pip install requests
+      - name: Delete existing release if exists
+        if: ${{ github.event.inputs.overwrite != 'false' }}
+        env:
+          VERSION: ${{ needs.prepare.outputs.version }}
+          TAG: ${{ needs.prepare.outputs.tag }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set +e
+
+          echo "Deleting release $TAG"
+          python3 .github/workflows/scripts/delete_gh_release.py --tag $TAG
+          if [ $? -ne 0 ]; then
+            echo "::error title=Delete release failed::Failed to delete existing release"
+            exit 1
+          fi
+
+          echo "Deleting tag $TAG"
+          git tag -d $TAG || true
+          git push --delete origin $TAG || true
+
+      - name: Prepare artifacts directory
+        run: mkdir -p artifacts
+      - name: Download jars
+        uses: actions/download-artifact@v3
+        with:
+          name: jars
+          path: artifacts/jars
+      - name: Download wheels
+        uses: actions/download-artifact@v3
+        with:
+          name: wheels
+          path: artifacts/wheels
+
+      - name: Create tag
+        env:
+          VERSION: ${{ needs.prepare.outputs.version }}
+          TAG: ${{ needs.prepare.outputs.tag }}
+        run: |
+          git tag $TAG
+          git push origin $TAG
+      - name: Create release
+        uses: softprops/action-gh-release@v2
+        with:
+          name: ${{ github.event.inputs.name != '' && github.event.inputs.name || needs.prepare.outputs.tag }}
+          tag_name: ${{ needs.prepare.outputs.tag }}
+          draft: false
+          prerelease: ${{ github.event.inputs.prerelease }}
+          make_latest: ${{ github.event.inputs.make_latest }}
+          fail_on_unmatched_files: true
+          generate_release_notes: true
+          files: |
+            artifacts/jars/*
+            artifacts/wheels/*
+            LICENSE
